[package]
name = "carbide_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carbide_rusttype = { path = "../carbide_rusttype" }
carbide_core = { path = "../../carbide_core" }
fxhash = "0.2.1"