[package]
name = "hacker_news"
version = "0.1.0"
edition = "2021"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carbide = { path = "../../carbide", features = ["controls"] }
reqwest = { version = "0.11.6", features = ["json"]}
futures = "0.3"
serde = { version = "1.0.133", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
open = "1"