[package]
name = "fractal"
version.workspace = true
repository.workspace = true
edition.workspace = true
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carbide = { path = "../../carbide", features = ["controls"] }
chrono = "0.4.19"
