[package]
name = "carbide"
version = "0.70.1"
authors = ["Holger Gott Christensen <hoch@itu.dk>"]
edition = "2021"
keywords = ["ui", "widgets", "gui", "interface", "graphics"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/HolgerGottChristensen/carbide.git"
homepage = "https://github.com/HolgerGottChristensen/carbide"
description = "A crate that includes the other carbide crates and where features can be selected"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["carbide_wgpu"]
controls = ["carbide_controls"]


[dependencies]
carbide_macro = { path = "../carbide_macro", version = "0.1.0" }
carbide_core = { path = "../carbide_core", version = "0.70", features = ["tokio"] }
carbide_controls = { path = "../carbide_controls", version = "0.70", optional = true }
carbide_wgpu = { path = "../backends/carbide_wgpu", version = "0.70", optional = true }

[dev-dependencies]
carbide_controls = { path = "../carbide_controls", version = "0.70" }
env_logger = "0.7"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.6", features = ["json"]}
futures = "0.3"
serde = { version = "1.0.133", features= ["derive"] }
chrono = "0.4.19"
open = "1"
num = "0.4.1"


arrayvec = "0.5.1"
rayon = "1.7.0"
uuid = { version = "1.4.1", features = ["v4"] }
rand = "0.8.5"

[[example]]
name = "animate_on_click"
required-features = ["controls"]
