[package]
name = "carbide_piston"
version = "0.70.0"
authors = [
    "Mitchell Nordine <mitchell.nordine@gmail.com>",
    "Sven Nilsen <bvssvni@gmail.com>"
]
keywords = ["ui", "widgets", "gui", "interface", "graphics"]
description = "An easy-to-use, 100% Rust, extensible 2D GUI library."
license = "MIT OR Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/HolgerGottChristensen/carbide.git"
homepage = "https://github.com/HolgerGottChristensen/carbide"
categories = ["gui"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "carbide_piston"
path = "./src/lib.rs"

[dependencies]
carbide_core = { path = "../../carbide_core", version = "0.70" }
piston2d-graphics = { version = "0.36" }
pistoncore-input = "1.0.0"

[dev-dependencies]
carbide_example_shared = { path = "../carbide_example_shared", version = "0.70" }
find_folder = "0.3.0"
image = "0.23"
petgraph = "0.4"
piston_window = "0.110"
